
  // this file was generated by build/icons.js
  // do not modify!
  import type { Component, JSX } from "solid-js"

  export const BtokenOutline: Component<JSX.SvgSVGAttributes<SVGSVGElement>> = (attrs = {}) => {
    return (<svg {...attrs} xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17.182 4.987A9.963 9.963 0 0 1 10 2.453a9.962 9.962 0 0 1-7.182 2.534C2.606 5.807 2.5 6.652 2.5 7.5c0 4.66 3.187 8.575 7.5 9.685 4.313-1.11 7.5-5.025 7.5-9.685 0-.868-.11-1.71-.318-2.513z"/></svg>)
  }
