
  // this file was generated by build/icons.js
  // do not modify!
  import type { Component, JSX } from "solid-js"

  export const Factory: Component<JSX.SvgSVGAttributes<SVGSVGElement>> = (attrs = {}) => {
    return (<svg {...attrs} xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" stroke-width="2" d="M5 21h14M18 3h3c.6 0 1 .4 1 1v16c0 .6-.4 1-1 1h-4V4c0-.6.4-1 1-1zM17 12H4c-1.1 0-2 .9-2 2v7h15v-9zM5 15h1M9 15h1M13 15h1M5 18h1M9 18h1M13 18h1M12.5 5h-1.8c-.3-.6-1-1-1.7-1s-1.4.4-1.7 1h-.4c-.2-1.1-1.2-2-2.4-2C3.1 3 2 4.1 2 5.5 2 6.8 3 7.8 4.2 8h8.3c.8 0 1.5-.7 1.5-1.5S13.3 5 12.5 5zM18 7h3"/></svg>)
  }
