
  // this file was generated by build/icons.js
  // do not modify!
  import type { Component, JSX } from "solid-js"

  export const FastForward: Component<JSX.SvgSVGAttributes<SVGSVGElement>> = (attrs = {}) => {
    return (<svg {...attrs} xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11.933 12.8a1 1 0 0 0 0-1.6L6.6 7.2A1 1 0 0 0 5 8v8a1 1 0 0 0 1.6.8l5.333-4zM19.933 12.8a1 1 0 0 0 0-1.6l-5.333-4A1 1 0 0 0 13 8v8a1 1 0 0 0 1.6.8l5.333-4z"/></svg>)
  }
