
  // this file was generated by build/icons.js
  // do not modify!
  import type { Component, JSX } from "solid-js"

  export const PaperPlane: Component<JSX.SvgSVGAttributes<SVGSVGElement>> = (attrs = {}) => {
    return (<svg {...attrs} xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 25" stroke="currentColor"><path stroke-linejoin="round" stroke-width="2" d="M20 4.5 2 11.73l7.26 3.54 3.555 7.23L20 4.5z"/><path stroke-width="2" d="m9 15.5 11-11"/></svg>)
  }
