
  // this file was generated by build/icons.js
  // do not modify!
  import type { Component, JSX } from "solid-js"

  export const Report: Component<JSX.SvgSVGAttributes<SVGSVGElement>> = (attrs = {}) => {
    return (<svg {...attrs} xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-width="2" d="M8.5 12h7m-7 3.429H12M8.5 8.57h7M5 6.095C5 4.938 5.958 4 7.139 4h9.722C18.042 4 19 4.938 19 6.095v11.81C19 19.062 18.042 20 16.861 20H7.14C5.958 20 5 19.062 5 17.905V6.095z"/></svg>)
  }
