
  // this file was generated by build/icons.js
  // do not modify!
  import type { Component, JSX } from "solid-js"

  export const Rss: Component<JSX.SvgSVGAttributes<SVGSVGElement>> = (attrs = {}) => {
    return (<svg {...attrs} xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 5c7.18 0 13 5.82 13 13M6 11a7 7 0 0 1 7 7m-6 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/></svg>)
  }
