
  // this file was generated by build/icons.js
  // do not modify!
  import type { Component, JSX } from "solid-js"

  export const Zero: Component<JSX.SvgSVGAttributes<SVGSVGElement>> = (attrs = {}) => {
    return (<svg {...attrs} xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor"><rect width="10" height="18" x="7" y="3" stroke-width="2" rx="5"/><path stroke-linecap="round" stroke-width="2" d="M19.233 2.395 5.395 21.767"/></svg>)
  }
