[project]
name = "resonite-mod-search"
version = "0.0.0"
authors = [{ name = "brecert", email = "me@bree.dev" }]
dependencies = [
    "jinja2>=3.1.2",
    "pydantic>=2.5.3",
    "python-slugify>=8.0.1",
]
requires-python = ">=3.11"
