
  // this file was generated by build/icons.js
  // do not modify!
  import type { Component, JSX } from "solid-js"

  export const Menu: Component<JSX.SvgSVGAttributes<SVGSVGElement>> = (attrs = {}) => {
    return (<svg {...attrs} xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"><path fill-rule="evenodd" d="M3 5a1 1 0 0 1 1-1h12a1 1 0 1 1 0 2H4a1 1 0 0 1-1-1zM3 10a1 1 0 0 1 1-1h12a1 1 0 1 1 0 2H4a1 1 0 0 1-1-1zM3 15a1 1 0 0 1 1-1h12a1 1 0 1 1 0 2H4a1 1 0 0 1-1-1z" clip-rule="evenodd"/></svg>)
  }
