
  // this file was generated by build/icons.js
  // do not modify!
  import type { Component, JSX } from "solid-js"

  export const Order: Component<JSX.SvgSVGAttributes<SVGSVGElement>> = (attrs = {}) => {
    return (<svg {...attrs} xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"><path stroke="currentColor" stroke-linecap="round" stroke-width="2" d="M7 8h5M7 11h3"/><path d="M9.517 16.298a1 1 0 1 0 0-2v2zm4.78-6.798a1 1 0 1 0 2 0h-2zm-9-5.202h8v-2h-8v2zm-1 9v-8h-2v8h2zm5.22 1h-4.22v2h4.22v-2zm4.78-9V9.5h2V5.298h-2zm-12 8a3 3 0 0 0 3 3v-2a1 1 0 0 1-1-1h-2zm11-9a1 1 0 0 1 1 1h2a3 3 0 0 0-3-3v2zm-8-2a3 3 0 0 0-3 3h2a1 1 0 0 1 1-1v-2z"/><path stroke="currentColor" stroke-linecap="round" stroke-width="2" d="M13.298 15h4M15.298 13v4"/></svg>)
  }
