
  // this file was generated by build/icons.js
  // do not modify!
  import type { Component, JSX } from "solid-js"

  export const Send: Component<JSX.SvgSVGAttributes<SVGSVGElement>> = (attrs = {}) => {
    return (<svg {...attrs} xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"><path stroke="currentColor" stroke-linejoin="round" stroke-width="2" d="M18 2 2 8.427l6.454 3.146L11.614 18 18 2z"/><path stroke="currentColor" stroke-width="2" d="M8 12 18 2"/></svg>)
  }
