
  // this file was generated by build/icons.js
  // do not modify!
  import type { Component, JSX } from "solid-js"

  export const UserRemove: Component<JSX.SvgSVGAttributes<SVGSVGElement>> = (attrs = {}) => {
    return (<svg {...attrs} xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"><path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0zM14 17a6 6 0 0 0-12 0h12zM13 8a1 1 0 1 0 0 2h4a1 1 0 1 0 0-2h-4z"/></svg>)
  }
